routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resources([
                  'setup' => App\Http\Controllers\SetupController::class,
                  'user' => App\Http\Controllers\UserController::class,
                  'object-manager' => App\Http\Controllers\ObjectManagerController::class,
                  'enviroment' => App\Http\Controllers\EnviromentController::class
                ]);

app/Models/Setup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setup extends Model
{
    use HasFactory;
}

app/Http/Controllers/SetupController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class SetupController extends Controller {
  private $path = 'setup';
  
  public function __construct() {
    $this->middleware('auth');
  }
    
  public function index() {
    $usr_id = Auth::id();
    $usr_env_id = Auth::user()->enviroment_id;
    $user_role_name = DB::select('call get_cur_user_type_name_by_usr_id('. $usr_env_id.', '. $usr_id .')')[0];
    /*
    $users_data = json_encode(DB::select('call get_all_users_by_env_id('. $usr_env_id .')'));
    $object_data = json_encode(DB::select('call get_all_objects_by_env_id('. $usr_env_id .')'));
    
    $enviroments_data = json_encode(DB::select('call get_all_enviroments()'));
    return view(
                $this->path, 
                compact(
                  'users_data',
                  'object_data',
                  'user_role_name',
                  'enviroments_data'
                )
              );
    */
    return view($this->path . '.index', compact('user_role_name'));
  }
}

resources/views/setup/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
          <a class="nav-link active" 
             id="v-pills-settings-tab"
             href="{{ route('setup.index') }}" >
            Setup
          </a>
          <a class="nav-link" 
             id="v-pills-users-tab"
             href="{{ route('user.index') }}" >
            Users
          </a>
          <a class="nav-link" 
             id="v-pills-object-manager-tab"
             href="{{ route('object-manager.index') }}" >
            Object Manager
          </a>
          @if ($user_role_name->role_type == 'Propietario')
          <a class="nav-link" 
             id="v-pills-enviroments-tab"
             href="{{ route('enviroment.index') }}" >
            Enviroments
          </a>
          @endif          
        </div>
      </div>
      <div class="col-md-8">
        <h3>Setup Description</h3>
        <ul>
          <li>Information about the org (Property).</li>
          <li>Information about the enviroment for the user (User).</li>
        </ul>
      </div>
    </div>
</div>
@endsection